services:
 web:
   image: vulhub/geoserver:2.22.1
   depends_on:
    - postgres
   ports:
    - "8080:8080"
   volumes:
     - ./startup.sh:/startup.sh
     - ./hook/java-agent.jar:/hook/java-agent.jar
     #- ./data:/mnt/geoserver/data_dir
     - ./hook/table_config.json:/tmp/table_config.json
     - ./logs:/tmp/logs
     - ../../rust_sqlparse_java/libjni_sql_rewriter.so:/libjni_sql_rewriter.so
   environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/hook/java-agent.jar"
   command: bash /startup.sh
 postgres:
   image: postgis-request-logger:13.12
   ports:
    - "5434:5432"
   environment: 
    - POSTGRES_PASSWORD=vulhub
    - POSTGRES_DB=geoserver
   volumes:
   - ./init-postgis.sql:/docker-entrypoint-initdb.d/init-postgis.sql
   #- ./pgdata:/var/lib/postgresql/data
   command:
    - "postgres"
    - "-c"
    - "wal_level=logical"
    - "-c"
    - "max_wal_senders=10"
    - "-c"
    - "max_replication_slots=10"
    - "-c"
    - "shared_preload_libraries=request_id_logger,wal2json"
    - "-c"
    - "wal_keep_size=256MB"
    - "-c"
    - "max_connections=100"
