services:
  app:
    image: kanboard/kanboard:v1.2.44
    container_name: kanboard
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./kanboard_data/data:/var/www/app/data
      - ./kanboard_data/plugins:/var/www/app/plugins
      - ./kanboard_data/certs:/etc/nginx/ssl
    environment:
      DATABASE_URL: postgres://kanboard:kanboard-secret@db/kanboard
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13.12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kanboard
      POSTGRES_PASSWORD: kanboard-secret
      POSTGRES_DB: kanboard
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kanboard"]
      start_period: 15s
      interval: 10s
      timeout: 5s
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "wal_keep_size=256MB"
      - "-c"
      - "max_connections=100"
