from __future__ import annotations

import bisect
import json
from collections import defaultdict, deque
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Protocol, Sequence

from .models import (
    CellCandidate,
    CellKey,
    CellLink,
    CellWrite,
    PrunedCell,
    ReadEvent,
    RowDelete,
    RowKey,
    TaintDecision,
    TraceResult,
    UnresolvedCell,
)

TimeEventKey = tuple[datetime, int]
XidEventKey = tuple[int, int]

DEFAULT_ATTACK_DESCRIPTION = (
    "The final request has been confirmed as abnormal or attacking; "
    "the specific attack type is unknown. Keep only cells that carry the "
    "attack payload or directly control attack propagation."
)


def _values_equal(left: object, right: object) -> bool:
    return type(left) is type(right) and left == right


class CellAnalyzer(Protocol):
    def judge_cells(
        self,
        *,
        root_rid: str,
        child_rid: str,
        attack_description: str,
        candidates: Sequence[CellCandidate],
    ) -> list[TaintDecision]:
        ...


def _normalize_attack_description(value: str | None) -> str:
    text = (value or "").strip()
    return text or DEFAULT_ATTACK_DESCRIPTION


@dataclass(frozen=True)
class PrunePolicy:
    """Noise-pruning policy learned from benign traffic.

    The policy suppresses dependency explosions from sessions and common
    tables/rows. Ablation showed that table-level GRAY was ineffective because
    row-level rules already cover its intended behavior, so it was removed.
    """

    block_tables: frozenset[str]
    block_rows: frozenset[RowKey]
    gray_rows: frozenset[RowKey]

    def decide(self, table: str, pk: str) -> str:
        """Return gray or keep.

        block has been downgraded to gray: dependencies are no longer deleted,
        but collapsed into one-hop non-recursive links.
        """
        t = table.lower()
        row = (t, str(pk))
        if row in self.block_rows or t in self.block_tables or row in self.gray_rows:
            return "gray"
        return "keep"


def load_prune_policy(path: str) -> PrunePolicy:
    """Load a policy JSON generated by pruning_algorithm.py.

    Older policy files may still contain gray_tables; this field is ignored.
    """
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    block_tables = frozenset(t.lower() for t in data.get("block_tables", []))

    def _parse_rows(items):
        rows = set()
        for item in items:
            if isinstance(item, dict):
                rows.add((str(item["table"]).lower(), str(item["pk"])))
            else:
                table, pk = str(item)[:-1].split("[", 1)
                rows.add((table.lower(), pk))
        return frozenset(rows)

    return PrunePolicy(
        block_tables=block_tables,
        block_rows=_parse_rows(data.get("block_rows", [])),
        gray_rows=_parse_rows(data.get("gray_rows", [])),
    )


@dataclass
class CellIndexes:
    histories: dict[CellKey, list[CellWrite]]
    history_keys: dict[CellKey, list[TimeEventKey]]
    origin_positions: dict[CellKey, list[int]]
    xid_histories: dict[CellKey, list[CellWrite]]
    xid_history_keys: dict[CellKey, list[XidEventKey]]
    xid_origin_positions: dict[CellKey, list[int]]
    row_cells: dict[RowKey, tuple[CellKey, ...]]
    row_delete_keys: dict[RowKey, list[TimeEventKey]]
    xid_row_delete_keys: dict[RowKey, list[XidEventKey]]
    rows_with_legacy_deletes: frozenset[RowKey]
    request_reads: dict[str, list[ReadEvent]]


def _build_origin_positions(history: Sequence[CellWrite]) -> list[int]:
    positions: list[int] = []
    for position, event in enumerate(history):
        if (
            position == 0
            or event.operation == "insert"
            or not _values_equal(history[position - 1].value, event.value)
        ):
            positions.append(position)
        else:
            positions.append(positions[position - 1])
    return positions


def build_indexes(
    reads: Sequence[ReadEvent],
    writes: Sequence[CellWrite],
    deletes: Sequence[RowDelete] = (),
) -> CellIndexes:
    histories: dict[CellKey, list[CellWrite]] = defaultdict(list)
    row_cells_mutable: dict[RowKey, set[CellKey]] = defaultdict(set)
    for write in writes:
        histories[write.cell].append(write)
        row_cells_mutable[write.row].add(write.cell)
    for history in histories.values():
        history.sort(key=lambda event: (event.time, event.sequence))

    origin_positions = {
        cell: _build_origin_positions(history)
        for cell, history in histories.items()
    }

    xid_histories: dict[CellKey, list[CellWrite]] = {}
    for cell, history in histories.items():
        if all(event.xid is not None for event in history):
            xid_histories[cell] = sorted(
                history, key=lambda event: (event.xid, event.sequence)
            )
    xid_origin_positions = {
        cell: _build_origin_positions(history)
        for cell, history in xid_histories.items()
    }

    delete_keys: dict[RowKey, list[TimeEventKey]] = defaultdict(list)
    for delete in deletes:
        delete_keys[delete.row].append((delete.time, delete.sequence))
    for keys in delete_keys.values():
        keys.sort()

    xid_delete_keys: dict[RowKey, list[XidEventKey]] = defaultdict(list)
    rows_with_legacy_deletes: set[RowKey] = set()
    for delete in deletes:
        if delete.xid is None:
            rows_with_legacy_deletes.add(delete.row)
        else:
            xid_delete_keys[delete.row].append((delete.xid, delete.sequence))
    for keys in xid_delete_keys.values():
        keys.sort()

    request_reads: dict[str, list[ReadEvent]] = defaultdict(list)
    for read in reads:
        request_reads[read.rid].append(read)
    for events in request_reads.values():
        events.sort(key=lambda event: (event.sequence, event.time))

    return CellIndexes(
        histories=dict(histories),
        history_keys={
            cell: [(event.time, event.sequence) for event in history]
            for cell, history in histories.items()
        },
        origin_positions=origin_positions,
        xid_histories=xid_histories,
        xid_history_keys={
            cell: [(event.xid, event.sequence) for event in history]
            for cell, history in xid_histories.items()
        },
        xid_origin_positions=xid_origin_positions,
        row_cells={
            row: tuple(sorted(cells))
            for row, cells in row_cells_mutable.items()
        },
        row_delete_keys=dict(delete_keys),
        xid_row_delete_keys=dict(xid_delete_keys),
        rows_with_legacy_deletes=frozenset(rows_with_legacy_deletes),
        request_reads=dict(request_reads),
    )


def _latest_delete_before(
    row: RowKey,
    read_time: datetime,
    indexes: CellIndexes,
) -> TimeEventKey | None:
    keys = indexes.row_delete_keys.get(row, ())
    position = bisect.bisect_right(keys, (read_time, 2**63 - 1)) - 1
    return keys[position] if position >= 0 else None


def _cell_version_at_time(
    cell: CellKey,
    read_time: datetime,
    indexes: CellIndexes,
) -> tuple[CellWrite, CellWrite] | None:
    keys = indexes.history_keys.get(cell)
    if not keys:
        return None
    position = bisect.bisect_right(keys, (read_time, 2**63 - 1)) - 1
    if position < 0:
        return None

    history = indexes.histories[cell]
    latest = history[position]
    delete_key = _latest_delete_before((cell[0], cell[1]), read_time, indexes)
    latest_key = (latest.time, latest.sequence)
    if delete_key is not None and latest_key <= delete_key:
        return None

    origin_position = indexes.origin_positions[cell][position]
    if delete_key is not None:
        # Deletion starts a new row lifetime even if the re-created value is equal.
        first_after_delete = bisect.bisect_right(keys, delete_key)
        origin_position = max(origin_position, first_after_delete)
    return latest, history[origin_position]


@dataclass(frozen=True)
class _ResolvedCellVersion:
    latest: CellWrite
    origin: CellWrite
    certainty: str
    reason: str
    alternate: CellWrite | None = None


def _cell_version_before_xid(
    cell: CellKey,
    xid_bound: int,
    indexes: CellIndexes,
) -> tuple[CellWrite, CellWrite, int] | None:
    keys = indexes.xid_history_keys.get(cell)
    if not keys:
        return None
    position = bisect.bisect_left(keys, (xid_bound, -1)) - 1
    if position < 0:
        return None

    history = indexes.xid_histories[cell]
    latest = history[position]
    delete_keys = indexes.xid_row_delete_keys.get((cell[0], cell[1]), ())
    delete_position = bisect.bisect_left(delete_keys, (xid_bound, -1)) - 1
    delete_key = delete_keys[delete_position] if delete_position >= 0 else None
    latest_key = (latest.xid, latest.sequence)
    if delete_key is not None and latest_key <= delete_key:
        return None

    origin_position = indexes.xid_origin_positions[cell][position]
    if delete_key is not None:
        first_after_delete = bisect.bisect_right(keys, delete_key)
        origin_position = max(origin_position, first_after_delete)
    return latest, history[origin_position], position


def _snapshot_cell_versions(
    cell: CellKey,
    read: ReadEvent,
    indexes: CellIndexes,
) -> list[_ResolvedCellVersion] | None:
    """Resolve Scheme D for one cell, or return None for legacy fallback."""
    if read.xmin is None or read.xmax is None:
        return None
    if cell not in indexes.xid_histories:
        return None
    if read.row in indexes.rows_with_legacy_deletes:
        return None

    low = _cell_version_before_xid(cell, read.xmin, indexes)
    high = _cell_version_before_xid(cell, read.xmax, indexes)
    if high is None:
        return []
    high_latest, high_origin, high_position = high

    history = indexes.xid_histories[cell]
    keys = indexes.xid_history_keys[cell]
    window_start = bisect.bisect_left(keys, (read.xmin, -1))
    window_end = bisect.bisect_left(keys, (read.xmax, -1))
    # A transaction may update the same cell more than once. Only its final
    # cell version can be visible outside that transaction, so retain the last
    # event for each xid while preserving every writer transaction in the
    # snapshot uncertainty window.
    window_positions = [
        position
        for position in range(window_start, window_end)
        if position + 1 == window_end
        or history[position + 1].xid != history[position].xid
    ]

    # Rule 0: a request's own committed write is causally local.
    if high_latest.rid == read.rid:
        return [_ResolvedCellVersion(
            high_latest, high_origin, "certain", "snapshot-rule-0-self-write"
        )]

    # Rule 1: because the read returned this row, the only available high-side
    # version must have been visible when no definitely-visible version exists.
    if low is None and high_latest.operation == "insert":
        return [_ResolvedCellVersion(
            high_latest, high_origin, "certain", "snapshot-rule-1-row-exists"
        )]
    if low is None:
        reason = "snapshot-incomplete-history-no-lower-bound"
        window_writes = [history[position] for position in window_positions]
        return [
            _ResolvedCellVersion(
                event,
                event,
                "uncertain",
                reason,
                (
                    window_writes[(index + 1) % len(window_writes)]
                    if len(window_writes) > 1
                    else None
                ),
            )
            for index, event in enumerate(window_writes)
        ]

    low_latest, low_origin, low_position = low
    if low_position == high_position:
        return [_ResolvedCellVersion(
            low_latest, low_origin, "certain", "snapshot-rule-2-no-window-write"
        )]

    # Rule 3: both boundaries land in the same continuous typed-value run.
    if (
        indexes.xid_origin_positions[cell][low_position]
        == indexes.xid_origin_positions[cell][high_position]
        and _values_equal(low_latest.value, high_latest.value)
    ):
        return [_ResolvedCellVersion(
            high_latest, high_origin, "certain", "snapshot-rule-3-same-value-origin"
        )]

    # Rule 4: without xip, any writer in [xmin, xmax) may be the latest visible
    # writer. Retain C_lo plus every writer in that interval, rather than only
    # the two boundary versions. None is recursively expanded.
    reason = "snapshot-rule-4-concurrent-window"
    uncertain_versions = [(low_latest, low_origin)] if low is not None else []
    # A window writer must remain a candidate writer in its own right. It is
    # not safe to fold it into an earlier same-value origin: that origin may
    # itself be an in-progress transaction that was invisible to the reader.
    uncertain_versions.extend(
        (history[position], history[position])
        for position in window_positions
    )
    return [
        _ResolvedCellVersion(
            latest,
            origin,
            "uncertain",
            reason,
            (
                uncertain_versions[(index + 1) % len(uncertain_versions)][0]
                if len(uncertain_versions) > 1
                else None
            ),
        )
        for index, (latest, origin) in enumerate(uncertain_versions)
    ]


def _cell_versions_for_read(
    cell: CellKey,
    read: ReadEvent,
    indexes: CellIndexes,
) -> list[_ResolvedCellVersion]:
    snapshot_versions = _snapshot_cell_versions(cell, read, indexes)
    if snapshot_versions is not None:
        return snapshot_versions
    legacy = _cell_version_at_time(cell, read.time, indexes)
    if legacy is None:
        return []
    latest, origin = legacy
    return [_ResolvedCellVersion(
        latest, origin, "certain", "legacy-time-fallback"
    )]


def _request_candidates(
    rid: str,
    indexes: CellIndexes,
) -> tuple[list[CellCandidate], list[UnresolvedCell]]:
    # Repeated reads of the same cell version are one dependency. If the cell
    # changes between two reads, both versions remain separate candidates.
    candidates: dict[
        tuple[CellKey, int | None, int, datetime, str], CellCandidate
    ] = {}
    unresolved: list[UnresolvedCell] = []
    unresolved_keys: set[tuple[RowKey, str | None, datetime, str]] = set()

    for read in indexes.request_reads.get(rid, ()):
        if read.observed_cells is None:
            cells = indexes.row_cells.get(read.row, ())
            if not cells:
                key = (read.row, None, read.time, "row has no available cell write history")
                if key not in unresolved_keys:
                    unresolved_keys.add(key)
                    unresolved.append(UnresolvedCell(rid, read.row, None, read.time, key[3]))
                continue
        else:
            cells = tuple(
                (read.table, read.pk, column)
                for column in sorted(read.observed_cells)
            )

        for cell in cells:
            versions = _cell_versions_for_read(cell, read, indexes)
            if not versions:
                reason = (
                    "no traceable version for this cell before the snapshot upper bound"
                    if read.xmin is not None and read.xmax is not None
                    else "no traceable version for this cell before the read time"
                )
                key = (read.row, cell[2], read.time, reason)
                if key not in unresolved_keys:
                    unresolved_keys.add(key)
                    unresolved.append(
                        UnresolvedCell(rid, read.row, cell[2], read.time, reason)
                    )
                continue

            if read.observed_cells is not None:
                observed_value = read.observed_cells[cell[2]]
                versions = [
                    version for version in versions
                    if _values_equal(observed_value, version.latest.value)
                ]
                if len(versions) == 1 and versions[0].certainty == "uncertain":
                    matched = versions[0]
                    versions = [_ResolvedCellVersion(
                        matched.latest,
                        matched.origin,
                        "certain",
                        "observed-value-disambiguation",
                    )]
                if not versions:
                    reason = "cell value in the read log does not match any snapshot candidate"
                    key = (read.row, cell[2], read.time, reason)
                    if key not in unresolved_keys:
                        unresolved_keys.add(key)
                        unresolved.append(
                            UnresolvedCell(rid, read.row, cell[2], read.time, reason)
                        )
                    continue

            for version in versions:
                value = (
                    read.observed_cells[cell[2]]
                    if read.observed_cells is not None
                    else version.latest.value
                )
                candidate = CellCandidate(
                    child_rid=rid,
                    cell=cell,
                    value=value,
                    read_event=read,
                    latest_write=version.latest,
                    origin_write=version.origin,
                    certainty=version.certainty,
                    resolution_reason=version.reason,
                    alternate_write=version.alternate,
                )
                candidate_key = (
                    cell,
                    version.latest.xid,
                    version.latest.sequence,
                    version.latest.time,
                    version.certainty,
                )
                old = candidates.get(candidate_key)
                if old is None or read.sequence < old.read_event.sequence:
                    candidates[candidate_key] = candidate

    return (
        sorted(
            candidates.values(),
            key=lambda item: (
                item.read_event.time,
                item.cell,
                item.latest_write.sequence,
                item.certainty,
            ),
        ),
        unresolved,
    )


def _should_recurse_gray(
    child_rid: str,
    candidate: CellCandidate,
    kept_candidates: Sequence[tuple[CellCandidate, str]],
    policy: PrunePolicy,
    is_root: bool,
) -> bool:
    """Decide whether to recurse through a gray dependency.

    block has been downgraded to gray: all noisy rows, including former block
    and gray rows, are kept as one-hop links without recursion. Direct
    dependencies of the root are the exception because the first step from the
    attack trigger must be expanded.
    """
    if is_root:
        return True
    return False


def build_cell_trace(
    root_rid: str,
    indexes: CellIndexes,
    *,
    analyzer: CellAnalyzer | None = None,
    attack_description: str | None = None,
    policy: PrunePolicy | None = None,
) -> TraceResult:
    if analyzer is not None and policy is not None:
        mode = "prune_llm"
    elif policy is not None:
        mode = "prune"
    elif analyzer is not None:
        mode = "llm"
    else:
        mode = "basic"
    attack_description = _normalize_attack_description(attack_description)

    queue = deque([str(root_rid)])
    visited: set[str] = set()
    links: list[CellLink] = []
    pruned: list[PrunedCell] = []
    unresolved: list[UnresolvedCell] = []
    suppressed: dict[str, int] = defaultdict(int)

    while queue:
        child_rid = queue.popleft()
        if child_rid in visited:
            continue
        visited.add(child_rid)

        candidates, request_unresolved = _request_candidates(child_rid, indexes)
        unresolved.extend(request_unresolved)

        # Step 1: apply structural pruning policy (gray/keep).
        # block has been downgraded to gray: all candidates keep one-hop links,
        # and noisy rows are collapsed rather than recursively expanded.
        if policy is not None:
            kept_candidates = [
                (cand, policy.decide(cand.cell[0], cand.cell[1]))
                for cand in candidates
            ]
        else:
            kept_candidates = [(cand, "keep") for cand in candidates]

        # Step 2: LLM taint analysis on surviving candidates (if enabled)
        if analyzer is None:
            decisions = [
                TaintDecision(
                    tainted=True,
                    confidence="not-applicable",
                    reason="basic mode keeps every resolvable cell dependency",
                )
                for _ in kept_candidates
            ]
        else:
            llm_input = [cand for cand, _ in kept_candidates]
            if llm_input:
                decisions = analyzer.judge_cells(
                    root_rid=str(root_rid),
                    child_rid=child_rid,
                    attack_description=attack_description,
                    candidates=llm_input,
                )
                if len(decisions) != len(llm_input):
                    raise RuntimeError(
                        f"cell decision count mismatch: candidates={len(llm_input)}, "
                        f"decisions={len(decisions)}"
                    )
            else:
                decisions = []

        # Step 3: build links + decide recursion
        for (cand, policy_decision), llm_decision in zip(kept_candidates, decisions):
            if not llm_decision.tainted:
                pruned.append(PrunedCell(cand, llm_decision))
                continue

            parent_rid = cand.origin_write.rid
            if parent_rid == child_rid:
                continue

            # Merge LLM decision with policy decision into the link's decision
            merged_reason = llm_decision.reason
            if policy_decision == "gray":
                merged_reason = f"[gray-show-without-recursion] {llm_decision.reason}"
            if cand.certainty == "uncertain":
                alternate = cand.alternate_write.rid if cand.alternate_write else "unknown"
                merged_reason = (
                    "[uncertain-concurrent-window-no-recursion; "
                    f"true last-writer candidates include {cand.origin_write.rid}/{alternate}] "
                    f"{merged_reason}"
                )

            link = CellLink(
                parent_rid=parent_rid,
                child_rid=child_rid,
                cell=cand.cell,
                value=cand.value,
                read_event=cand.read_event,
                latest_write=cand.latest_write,
                origin_write=cand.origin_write,
                decision=TaintDecision(
                    tainted=True,
                    confidence=llm_decision.confidence,
                    reason=merged_reason,
                    evidence=llm_decision.evidence,
                    model=llm_decision.model,
                    raw_response=llm_decision.raw_response,
                ),
                certainty=cand.certainty,
                resolution_reason=cand.resolution_reason,
                alternate_write=cand.alternate_write,
            )
            links.append(link)

            # gray candidates: show link but don't recurse (unless it's the
            # root's only dependency or parent has real business writes)
            should_recurse = True
            if cand.certainty == "uncertain":
                should_recurse = False
                suppressed["uncertain-no-recurse"] += 1
            if policy_decision == "gray":
                gray_recurse = _should_recurse_gray(
                    child_rid, cand, kept_candidates, policy, child_rid == str(root_rid)
                )
                should_recurse = should_recurse and gray_recurse
                if not gray_recurse:
                    suppressed["gray-no-recurse"] += 1

            if should_recurse and parent_rid not in visited:
                queue.append(parent_rid)

    return TraceResult(
        root_rid=str(root_rid),
        mode=mode,
        links=links,
        visited_requests=visited,
        pruned_cells=pruned,
        unresolved_cells=unresolved,
        suppressed=dict(suppressed),
    )
