/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sql_SqlRewriter */

#ifndef _Included_com_example_sql_SqlRewriter
#define _Included_com_example_sql_SqlRewriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sql_SqlRewriter
 * Method:    initConfig
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_sql_SqlRewriter_initConfig
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_sql_SqlRewriter
 * Method:    rewriteSql
 * Signature: (Ljava/lang/String;)Lcom/example/sql/RewriteResult;
 */
JNIEXPORT jobject JNICALL Java_com_example_sql_SqlRewriter_rewriteSql
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
