<?php
// File name: lib/dml/RustSqlRewriter.php

const INSTRUMENT_TABLE_CONFIG = [
    ["table" => "mdl_config", "pk" => "id"],
    ["table" => "mdl_config_plugins", "pk" => "id"],
    ["table" => "mdl_config_log", "pk" => "id"],
    ["table" => "mdl_upgrade_log", "pk" => "id"],
    ["table" => "mdl_course", "pk" => "id"],
    ["table" => "mdl_course_categories", "pk" => "id"],
    ["table" => "mdl_course_completion_aggr_methd", "pk" => "id"],
    ["table" => "mdl_course_completion_criteria", "pk" => "id"],
    ["table" => "mdl_course_completion_crit_compl", "pk" => "id"],
    ["table" => "mdl_course_completions", "pk" => "id"],
    ["table" => "mdl_communication", "pk" => "id"],
    ["table" => "mdl_communication_user", "pk" => "id"],
    ["table" => "mdl_enrol", "pk" => "id"],
    ["table" => "mdl_user_enrolments", "pk" => "id"],
    ["table" => "mdl_course_modules", "pk" => "id"],
    ["table" => "mdl_course_modules_completion", "pk" => "id"],
    ["table" => "mdl_course_sections", "pk" => "id"],
    ["table" => "mdl_course_request", "pk" => "id"],
    ["table" => "mdl_course_format_options", "pk" => "id"],
    ["table" => "mdl_filter_active", "pk" => "id"],
    ["table" => "mdl_filter_config", "pk" => "id"],
    ["table" => "mdl_event", "pk" => "id"],
    ["table" => "mdl_cache_filters", "pk" => "id"],
    ["table" => "mdl_log", "pk" => "id"],
    ["table" => "mdl_log_queries", "pk" => "id"],
    ["table" => "mdl_log_display", "pk" => "id"],
    ["table" => "mdl_message", "pk" => "id"],
    ["table" => "mdl_message_read", "pk" => "id"],
    ["table" => "mdl_messages", "pk" => "id"],
    ["table" => "mdl_message_conversations", "pk" => "id"],
    ["table" => "mdl_message_conversation_members", "pk" => "id"],
    ["table" => "mdl_message_conversation_actions", "pk" => "id"],
    ["table" => "mdl_message_user_actions", "pk" => "id"],
    ["table" => "mdl_notifications", "pk" => "id"],
    ["table" => "mdl_message_contacts", "pk" => "id"],
    ["table" => "mdl_message_contact_requests", "pk" => "id"],
    ["table" => "mdl_message_users_blocked", "pk" => "id"],
    ["table" => "mdl_modules", "pk" => "id"],
    ["table" => "mdl_my_pages", "pk" => "id"],
    ["table" => "mdl_sessions", "pk" => "id"],
    ["table" => "mdl_user", "pk" => "id"],
    ["table" => "mdl_user_preferences", "pk" => "id"],
    ["table" => "mdl_user_lastaccess", "pk" => "id"],
    ["table" => "mdl_user_password_history", "pk" => "id"],
    ["table" => "mdl_scale", "pk" => "id"],
    ["table" => "mdl_scale_history", "pk" => "id"],
    ["table" => "mdl_stats_daily", "pk" => "id"],
    ["table" => "mdl_stats_weekly", "pk" => "id"],
    ["table" => "mdl_stats_monthly", "pk" => "id"],
    ["table" => "mdl_stats_user_daily", "pk" => "id"],
    ["table" => "mdl_stats_user_weekly", "pk" => "id"],
    ["table" => "mdl_stats_user_monthly", "pk" => "id"],
    ["table" => "mdl_post", "pk" => "id"],
    ["table" => "mdl_role", "pk" => "id"],
    ["table" => "mdl_context", "pk" => "id"],
    ["table" => "mdl_context_temp", "pk" => "id"],
    ["table" => "mdl_capabilities", "pk" => "id"],
    ["table" => "mdl_role_allow_assign", "pk" => "id"],
    ["table" => "mdl_role_allow_override", "pk" => "id"],
    ["table" => "mdl_role_allow_switch", "pk" => "id"],
    ["table" => "mdl_role_allow_view", "pk" => "id"],
    ["table" => "mdl_role_assignments", "pk" => "id"],
    ["table" => "mdl_role_capabilities", "pk" => "id"],
    ["table" => "mdl_role_names", "pk" => "id"],
    ["table" => "mdl_role_context_levels", "pk" => "id"],
    ["table" => "mdl_user_info_field", "pk" => "id"],
    ["table" => "mdl_user_info_category", "pk" => "id"],
    ["table" => "mdl_user_info_data", "pk" => "id"],
    ["table" => "mdl_question_categories", "pk" => "id"],
    ["table" => "mdl_question", "pk" => "id"],
    ["table" => "mdl_question_bank_entries", "pk" => "id"],
    ["table" => "mdl_question_versions", "pk" => "id"],
    ["table" => "mdl_question_references", "pk" => "id"],
    ["table" => "mdl_question_set_references", "pk" => "id"],
    ["table" => "mdl_question_answers", "pk" => "id"],
    ["table" => "mdl_question_hints", "pk" => "id"],
    ["table" => "mdl_question_usages", "pk" => "id"],
    ["table" => "mdl_question_attempts", "pk" => "id"],
    ["table" => "mdl_question_attempt_steps", "pk" => "id"],
    ["table" => "mdl_question_attempt_step_data", "pk" => "id"],
    ["table" => "mdl_question_statistics", "pk" => "id"],
    ["table" => "mdl_question_response_analysis", "pk" => "id"],
    ["table" => "mdl_question_response_count", "pk" => "id"],
    ["table" => "mdl_mnet_application", "pk" => "id"],
    ["table" => "mdl_mnet_host", "pk" => "id"],
    ["table" => "mdl_mnet_host2service", "pk" => "id"],
    ["table" => "mdl_mnet_log", "pk" => "id"],
    ["table" => "mdl_mnet_rpc", "pk" => "id"],
    ["table" => "mdl_mnet_remote_rpc", "pk" => "id"],
    ["table" => "mdl_mnet_service", "pk" => "id"],
    ["table" => "mdl_mnet_service2rpc", "pk" => "id"],
    ["table" => "mdl_mnet_remote_service2rpc", "pk" => "id"],
    ["table" => "mdl_mnet_session", "pk" => "id"],
    ["table" => "mdl_mnet_sso_access_control", "pk" => "id"],
    ["table" => "mdl_events_queue", "pk" => "id"],
    ["table" => "mdl_events_handlers", "pk" => "id"],
    ["table" => "mdl_events_queue_handlers", "pk" => "id"],
    ["table" => "mdl_grade_outcomes", "pk" => "id"],
    ["table" => "mdl_grade_outcomes_courses", "pk" => "id"],
    ["table" => "mdl_grade_categories", "pk" => "id"],
    ["table" => "mdl_grade_items", "pk" => "id"],
    ["table" => "mdl_grade_grades", "pk" => "id"],
    ["table" => "mdl_grade_outcomes_history", "pk" => "id"],
    ["table" => "mdl_grade_categories_history", "pk" => "id"],
    ["table" => "mdl_grade_items_history", "pk" => "id"],
    ["table" => "mdl_grade_grades_history", "pk" => "id"],
    ["table" => "mdl_grade_import_newitem", "pk" => "id"],
    ["table" => "mdl_grade_import_values", "pk" => "id"],
    ["table" => "mdl_tag_coll", "pk" => "id"],
    ["table" => "mdl_tag_area", "pk" => "id"],
    ["table" => "mdl_tag", "pk" => "id"],
    ["table" => "mdl_tag_correlation", "pk" => "id"],
    ["table" => "mdl_tag_instance", "pk" => "id"],
    ["table" => "mdl_groups", "pk" => "id"],
    ["table" => "mdl_groupings", "pk" => "id"],
    ["table" => "mdl_groups_members", "pk" => "id"],
    ["table" => "mdl_groupings_groups", "pk" => "id"],
    ["table" => "mdl_cohort", "pk" => "id"],
    ["table" => "mdl_cohort_members", "pk" => "id"],
    ["table" => "mdl_user_private_key", "pk" => "id"],
    ["table" => "mdl_grade_letters", "pk" => "id"],
    ["table" => "mdl_cache_flags", "pk" => "id"],
    ["table" => "mdl_grade_settings", "pk" => "id"],
    ["table" => "mdl_portfolio_instance", "pk" => "id"],
    ["table" => "mdl_portfolio_instance_config", "pk" => "id"],
    ["table" => "mdl_portfolio_instance_user", "pk" => "id"],
    ["table" => "mdl_portfolio_log", "pk" => "id"],
    ["table" => "mdl_portfolio_tempdata", "pk" => "id"],
    ["table" => "mdl_message_providers", "pk" => "id"],
    ["table" => "mdl_message_processors", "pk" => "id"],
    ["table" => "mdl_files", "pk" => "id"],
    ["table" => "mdl_files_reference", "pk" => "id"],
    ["table" => "mdl_file_conversion", "pk" => "id"],
    ["table" => "mdl_repository", "pk" => "id"],
    ["table" => "mdl_repository_instances", "pk" => "id"],
    ["table" => "mdl_repository_instance_config", "pk" => "id"],
    ["table" => "mdl_backup_courses", "pk" => "id"],
    ["table" => "mdl_block", "pk" => "id"],
    ["table" => "mdl_block_instances", "pk" => "id"],
    ["table" => "mdl_block_positions", "pk" => "id"],
    ["table" => "mdl_comments", "pk" => "id"],
    ["table" => "mdl_external_services", "pk" => "id"],
    ["table" => "mdl_external_functions", "pk" => "id"],
    ["table" => "mdl_external_services_functions", "pk" => "id"],
    ["table" => "mdl_external_services_users", "pk" => "id"],
    ["table" => "mdl_external_tokens", "pk" => "id"],
    ["table" => "mdl_blog_association", "pk" => "id"],
    ["table" => "mdl_blog_external", "pk" => "id"],
    ["table" => "mdl_rating", "pk" => "id"],
    ["table" => "mdl_license", "pk" => "id"],
    ["table" => "mdl_registration_hubs", "pk" => "id"],
    ["table" => "mdl_backup_controllers", "pk" => "id"],
    ["table" => "mdl_backup_logs", "pk" => "id"],
    ["table" => "mdl_profiling", "pk" => "id"],
    ["table" => "mdl_course_published", "pk" => "id"],
    ["table" => "mdl_grading_areas", "pk" => "id"],
    ["table" => "mdl_grading_definitions", "pk" => "id"],
    ["table" => "mdl_grading_instances", "pk" => "id"],
    ["table" => "mdl_event_subscriptions", "pk" => "id"],
    ["table" => "mdl_badge", "pk" => "id"],
    ["table" => "mdl_badge_criteria", "pk" => "id"],
    ["table" => "mdl_badge_criteria_param", "pk" => "id"],
    ["table" => "mdl_badge_issued", "pk" => "id"],
    ["table" => "mdl_badge_criteria_met", "pk" => "id"],
    ["table" => "mdl_badge_endorsement", "pk" => "id"],
    ["table" => "mdl_badge_manual_award", "pk" => "id"],
    ["table" => "mdl_badge_backpack", "pk" => "id"],
    ["table" => "mdl_badge_backpack_oauth2", "pk" => "id"],
    ["table" => "mdl_badge_external", "pk" => "id"],
    ["table" => "mdl_badge_external_identifier", "pk" => "id"],
    ["table" => "mdl_badge_alignment", "pk" => "id"],
    ["table" => "mdl_badge_related", "pk" => "id"],
    ["table" => "mdl_badge_external_backpack", "pk" => "id"],
    ["table" => "mdl_user_devices", "pk" => "id"],
    ["table" => "mdl_user_password_resets", "pk" => "id"],
    ["table" => "mdl_lock_db", "pk" => "id"],
    ["table" => "mdl_task_scheduled", "pk" => "id"],
    ["table" => "mdl_task_adhoc", "pk" => "id"],
    ["table" => "mdl_task_log", "pk" => "id"],
    ["table" => "mdl_messageinbound_handlers", "pk" => "id"],
    ["table" => "mdl_messageinbound_datakeys", "pk" => "id"],
    ["table" => "mdl_messageinbound_messagelist", "pk" => "id"],
    ["table" => "mdl_competency", "pk" => "id"],
    ["table" => "mdl_competency_coursecompsetting", "pk" => "id"],
    ["table" => "mdl_competency_framework", "pk" => "id"],
    ["table" => "mdl_competency_coursecomp", "pk" => "id"],
    ["table" => "mdl_competency_plan", "pk" => "id"],
    ["table" => "mdl_competency_template", "pk" => "id"],
    ["table" => "mdl_competency_templatecomp", "pk" => "id"],
    ["table" => "mdl_competency_templatecohort", "pk" => "id"],
    ["table" => "mdl_competency_relatedcomp", "pk" => "id"],
    ["table" => "mdl_competency_usercomp", "pk" => "id"],
    ["table" => "mdl_competency_usercompcourse", "pk" => "id"],
    ["table" => "mdl_competency_usercompplan", "pk" => "id"],
    ["table" => "mdl_competency_plancomp", "pk" => "id"],
    ["table" => "mdl_competency_evidence", "pk" => "id"],
    ["table" => "mdl_competency_userevidence", "pk" => "id"],
    ["table" => "mdl_competency_userevidencecomp", "pk" => "id"],
    ["table" => "mdl_competency_modulecomp", "pk" => "id"],
    ["table" => "mdl_oauth2_endpoint", "pk" => "id"],
    ["table" => "mdl_oauth2_issuer", "pk" => "id"],
    ["table" => "mdl_oauth2_system_account", "pk" => "id"],
    ["table" => "mdl_oauth2_user_field_mapping", "pk" => "id"],
    ["table" => "mdl_course_completion_defaults", "pk" => "id"],
    ["table" => "mdl_analytics_models", "pk" => "id"],
    ["table" => "mdl_analytics_models_log", "pk" => "id"],
    ["table" => "mdl_analytics_predictions", "pk" => "id"],
    ["table" => "mdl_analytics_train_samples", "pk" => "id"],
    ["table" => "mdl_analytics_predict_samples", "pk" => "id"],
    ["table" => "mdl_analytics_used_files", "pk" => "id"],
    ["table" => "mdl_analytics_indicator_calc", "pk" => "id"],
    ["table" => "mdl_analytics_prediction_actions", "pk" => "id"],
    ["table" => "mdl_oauth2_access_token", "pk" => "id"],
    ["table" => "mdl_analytics_used_analysables", "pk" => "id"],
    ["table" => "mdl_search_index_requests", "pk" => "id"],
    ["table" => "mdl_favourite", "pk" => "id"],
    ["table" => "mdl_customfield_category", "pk" => "id"],
    ["table" => "mdl_customfield_field", "pk" => "id"],
    ["table" => "mdl_customfield_data", "pk" => "id"],
    ["table" => "mdl_h5p_libraries", "pk" => "id"],
    ["table" => "mdl_h5p_library_dependencies", "pk" => "id"],
    ["table" => "mdl_h5p", "pk" => "id"],
    ["table" => "mdl_h5p_contents_libraries", "pk" => "id"],
    ["table" => "mdl_h5p_libraries_cachedassets", "pk" => "id"],
    ["table" => "mdl_contentbank_content", "pk" => "id"],
    ["table" => "mdl_payment_accounts", "pk" => "id"],
    ["table" => "mdl_payment_gateways", "pk" => "id"],
    ["table" => "mdl_payments", "pk" => "id"],
    ["table" => "mdl_infected_files", "pk" => "id"],
    ["table" => "mdl_oauth2_refresh_token", "pk" => "id"],
    ["table" => "mdl_reportbuilder_report", "pk" => "id"],
    ["table" => "mdl_reportbuilder_column", "pk" => "id"],
    ["table" => "mdl_reportbuilder_filter", "pk" => "id"],
    ["table" => "mdl_reportbuilder_audience", "pk" => "id"],
    ["table" => "mdl_reportbuilder_schedule", "pk" => "id"],
    ["table" => "mdl_adminpresets", "pk" => "id"],
    ["table" => "mdl_adminpresets_it", "pk" => "id"],
    ["table" => "mdl_adminpresets_it_a", "pk" => "id"],
    ["table" => "mdl_adminpresets_app", "pk" => "id"],
    ["table" => "mdl_adminpresets_app_it", "pk" => "id"],
    ["table" => "mdl_adminpresets_app_it_a", "pk" => "id"],
    ["table" => "mdl_adminpresets_plug", "pk" => "id"],
    ["table" => "mdl_adminpresets_app_plug", "pk" => "id"],
    ["table" => "mdl_course_modules_viewed", "pk" => "id"],
    ["table" => "mdl_xapi_states", "pk" => "id"],
    ["table" => "mdl_moodlenet_share_progress", "pk" => "id"],
    ["table" => "mdl_question_calculated", "pk" => "id"],
    ["table" => "mdl_question_calculated_options", "pk" => "id"],
    ["table" => "mdl_question_dataset_definitions", "pk" => "id"],
    ["table" => "mdl_question_dataset_items", "pk" => "id"],
    ["table" => "mdl_question_datasets", "pk" => "id"],
    ["table" => "mdl_qtype_ddimageortext", "pk" => "id"],
    ["table" => "mdl_qtype_ddimageortext_drops", "pk" => "id"],
    ["table" => "mdl_qtype_ddimageortext_drags", "pk" => "id"],
    ["table" => "mdl_qtype_ddmarker", "pk" => "id"],
    ["table" => "mdl_qtype_ddmarker_drops", "pk" => "id"],
    ["table" => "mdl_qtype_ddmarker_drags", "pk" => "id"],
    ["table" => "mdl_question_ddwtos", "pk" => "id"],
    ["table" => "mdl_qtype_essay_options", "pk" => "id"],
    ["table" => "mdl_question_gapselect", "pk" => "id"],
    ["table" => "mdl_qtype_match_options", "pk" => "id"],
    ["table" => "mdl_qtype_match_subquestions", "pk" => "id"],
    ["table" => "mdl_question_multianswer", "pk" => "id"],
    ["table" => "mdl_qtype_multichoice_options", "pk" => "id"],
    ["table" => "mdl_question_numerical", "pk" => "id"],
    ["table" => "mdl_question_numerical_options", "pk" => "id"],
    ["table" => "mdl_question_numerical_units", "pk" => "id"],
    ["table" => "mdl_qtype_randomsamatch_options", "pk" => "id"],
    ["table" => "mdl_qtype_shortanswer_options", "pk" => "id"],
    ["table" => "mdl_question_truefalse", "pk" => "id"],
    ["table" => "mdl_assign", "pk" => "id"],
    ["table" => "mdl_assign_submission", "pk" => "id"],
    ["table" => "mdl_assign_grades", "pk" => "id"],
    ["table" => "mdl_assign_plugin_config", "pk" => "id"],
    ["table" => "mdl_assign_user_mapping", "pk" => "id"],
    ["table" => "mdl_assign_user_flags", "pk" => "id"],
    ["table" => "mdl_assign_overrides", "pk" => "id"],
    ["table" => "mdl_bigbluebuttonbn", "pk" => "id"],
    ["table" => "mdl_bigbluebuttonbn_logs", "pk" => "id"],
    ["table" => "mdl_bigbluebuttonbn_recordings", "pk" => "id"],
    ["table" => "mdl_book", "pk" => "id"],
    ["table" => "mdl_book_chapters", "pk" => "id"],
    ["table" => "mdl_chat", "pk" => "id"],
    ["table" => "mdl_chat_messages", "pk" => "id"],
    ["table" => "mdl_chat_messages_current", "pk" => "id"],
    ["table" => "mdl_chat_users", "pk" => "id"],
    ["table" => "mdl_choice", "pk" => "id"],
    ["table" => "mdl_choice_options", "pk" => "id"],
    ["table" => "mdl_choice_answers", "pk" => "id"],
    ["table" => "mdl_data", "pk" => "id"],
    ["table" => "mdl_data_fields", "pk" => "id"],
    ["table" => "mdl_data_records", "pk" => "id"],
    ["table" => "mdl_data_content", "pk" => "id"],
    ["table" => "mdl_feedback", "pk" => "id"],
    ["table" => "mdl_feedback_template", "pk" => "id"],
    ["table" => "mdl_feedback_item", "pk" => "id"],
    ["table" => "mdl_feedback_completed", "pk" => "id"],
    ["table" => "mdl_feedback_completedtmp", "pk" => "id"],
    ["table" => "mdl_feedback_value", "pk" => "id"],
    ["table" => "mdl_feedback_valuetmp", "pk" => "id"],
    ["table" => "mdl_feedback_sitecourse_map", "pk" => "id"],
    ["table" => "mdl_folder", "pk" => "id"],
    ["table" => "mdl_forum", "pk" => "id"],
    ["table" => "mdl_forum_discussions", "pk" => "id"],
    ["table" => "mdl_forum_posts", "pk" => "id"],
    ["table" => "mdl_forum_queue", "pk" => "id"],
    ["table" => "mdl_forum_subscriptions", "pk" => "id"],
    ["table" => "mdl_forum_digests", "pk" => "id"],
    ["table" => "mdl_forum_read", "pk" => "id"],
    ["table" => "mdl_forum_track_prefs", "pk" => "id"],
    ["table" => "mdl_forum_discussion_subs", "pk" => "id"],
    ["table" => "mdl_forum_grades", "pk" => "id"],
    ["table" => "mdl_glossary", "pk" => "id"],
    ["table" => "mdl_glossary_entries", "pk" => "id"],
    ["table" => "mdl_glossary_alias", "pk" => "id"],
    ["table" => "mdl_glossary_categories", "pk" => "id"],
    ["table" => "mdl_glossary_entries_categories", "pk" => "id"],
    ["table" => "mdl_glossary_formats", "pk" => "id"],
    ["table" => "mdl_h5pactivity", "pk" => "id"],
    ["table" => "mdl_h5pactivity_attempts", "pk" => "id"],
    ["table" => "mdl_h5pactivity_attempts_results", "pk" => "id"],
    ["table" => "mdl_imscp", "pk" => "id"],
    ["table" => "mdl_label", "pk" => "id"],
    ["table" => "mdl_lesson", "pk" => "id"],
    ["table" => "mdl_lesson_pages", "pk" => "id"],
    ["table" => "mdl_lesson_answers", "pk" => "id"],
    ["table" => "mdl_lesson_attempts", "pk" => "id"],
    ["table" => "mdl_lesson_grades", "pk" => "id"],
    ["table" => "mdl_lesson_timer", "pk" => "id"],
    ["table" => "mdl_lesson_branch", "pk" => "id"],
    ["table" => "mdl_lesson_overrides", "pk" => "id"],
    ["table" => "mdl_lti", "pk" => "id"],
    ["table" => "mdl_lti_tool_proxies", "pk" => "id"],
    ["table" => "mdl_lti_types", "pk" => "id"],
    ["table" => "mdl_lti_types_config", "pk" => "id"],
    ["table" => "mdl_lti_tool_settings", "pk" => "id"],
    ["table" => "mdl_lti_submission", "pk" => "id"],
    ["table" => "mdl_lti_access_tokens", "pk" => "id"],
    ["table" => "mdl_lti_types_categories", "pk" => "id"],
    ["table" => "mdl_lti_coursevisible", "pk" => "id"],
    ["table" => "mdl_page", "pk" => "id"],
    ["table" => "mdl_quiz", "pk" => "id"],
    ["table" => "mdl_quiz_slots", "pk" => "id"],
    ["table" => "mdl_quiz_sections", "pk" => "id"],
    ["table" => "mdl_quiz_feedback", "pk" => "id"],
    ["table" => "mdl_quiz_overrides", "pk" => "id"],
    ["table" => "mdl_quiz_attempts", "pk" => "id"],
    ["table" => "mdl_quiz_grades", "pk" => "id"],
    ["table" => "mdl_quiz_reports", "pk" => "id"],
    ["table" => "mdl_resource", "pk" => "id"],
    ["table" => "mdl_resource_old", "pk" => "id"],
    ["table" => "mdl_scorm", "pk" => "id"],
    ["table" => "mdl_scorm_scoes", "pk" => "id"],
    ["table" => "mdl_scorm_scoes_data", "pk" => "id"],
    ["table" => "mdl_scorm_seq_objective", "pk" => "id"],
    ["table" => "mdl_scorm_seq_mapinfo", "pk" => "id"],
    ["table" => "mdl_scorm_seq_ruleconds", "pk" => "id"],
    ["table" => "mdl_scorm_seq_rulecond", "pk" => "id"],
    ["table" => "mdl_scorm_seq_rolluprule", "pk" => "id"],
    ["table" => "mdl_scorm_seq_rolluprulecond", "pk" => "id"],
    ["table" => "mdl_scorm_aicc_session", "pk" => "id"],
    ["table" => "mdl_scorm_attempt", "pk" => "id"],
    ["table" => "mdl_scorm_element", "pk" => "id"],
    ["table" => "mdl_scorm_scoes_value", "pk" => "id"],
    ["table" => "mdl_survey", "pk" => "id"],
    ["table" => "mdl_survey_questions", "pk" => "id"],
    ["table" => "mdl_survey_answers", "pk" => "id"],
    ["table" => "mdl_survey_analysis", "pk" => "id"],
    ["table" => "mdl_url", "pk" => "id"],
    ["table" => "mdl_wiki", "pk" => "id"],
    ["table" => "mdl_wiki_subwikis", "pk" => "id"],
    ["table" => "mdl_wiki_pages", "pk" => "id"],
    ["table" => "mdl_wiki_versions", "pk" => "id"],
    ["table" => "mdl_wiki_synonyms", "pk" => "id"],
    ["table" => "mdl_wiki_links", "pk" => "id"],
    ["table" => "mdl_wiki_locks", "pk" => "id"],
    ["table" => "mdl_workshop", "pk" => "id"],
    ["table" => "mdl_workshop_submissions", "pk" => "id"],
    ["table" => "mdl_workshop_assessments", "pk" => "id"],
    ["table" => "mdl_workshop_grades", "pk" => "id"],
    ["table" => "mdl_workshop_aggregations", "pk" => "id"],
    ["table" => "mdl_auth_lti_linked_login", "pk" => "id"],
    ["table" => "mdl_auth_oauth2_linked_login", "pk" => "id"],
    ["table" => "mdl_communication_customlink", "pk" => "id"],
    ["table" => "mdl_matrix_room", "pk" => "id"],
    ["table" => "mdl_enrol_flatfile", "pk" => "id"],
    ["table" => "mdl_enrol_lti_tools", "pk" => "id"],
    ["table" => "mdl_enrol_lti_users", "pk" => "id"],
    ["table" => "mdl_enrol_lti_lti2_consumer", "pk" => "id"],
    ["table" => "mdl_enrol_lti_lti2_tool_proxy", "pk" => "id"],
    ["table" => "mdl_enrol_lti_lti2_context", "pk" => "id"],
    ["table" => "mdl_enrol_lti_lti2_nonce", "pk" => "id"],
    ["table" => "mdl_enrol_lti_lti2_resource_link", "pk" => "id"],
    ["table" => "mdl_enrol_lti_lti2_share_key", "pk" => "id"],
    ["table" => "mdl_enrol_lti_lti2_user_result", "pk" => "id"],
    ["table" => "mdl_enrol_lti_tool_consumer_map", "pk" => "id"],
    ["table" => "mdl_enrol_lti_app_registration", "pk" => "id"],
    ["table" => "mdl_enrol_lti_deployment", "pk" => "id"],
    ["table" => "mdl_enrol_lti_resource_link", "pk" => "id"],
    ["table" => "mdl_enrol_lti_context", "pk" => "id"],
    ["table" => "mdl_enrol_lti_user_resource_link", "pk" => "id"],
    ["table" => "mdl_enrol_paypal", "pk" => "id"],
    ["table" => "mdl_message_airnotifier_devices", "pk" => "id"],
    ["table" => "mdl_message_email_messages", "pk" => "id"],
    ["table" => "mdl_message_popup", "pk" => "id"],
    ["table" => "mdl_message_popup_notifications", "pk" => "id"],
    ["table" => "mdl_block_recent_activity", "pk" => "id"],
    ["table" => "mdl_block_recentlyaccesseditems", "pk" => "id"],
    ["table" => "mdl_block_rss_client", "pk" => "id"],
    ["table" => "mdl_editor_atto_autosave", "pk" => "id"],
    ["table" => "mdl_gradingform_guide_criteria", "pk" => "id"],
    ["table" => "mdl_gradingform_guide_fillings", "pk" => "id"],
    ["table" => "mdl_gradingform_guide_comments", "pk" => "id"],
    ["table" => "mdl_gradingform_rubric_criteria", "pk" => "id"],
    ["table" => "mdl_gradingform_rubric_levels", "pk" => "id"],
    ["table" => "mdl_gradingform_rubric_fillings", "pk" => "id"],
    ["table" => "mdl_mnetservice_enrol_courses", "pk" => "id"],
    ["table" => "mdl_mnetservice_enrol_enrolments", "pk" => "id"],
    ["table" => "mdl_repository_onedrive_access", "pk" => "id"],
    ["table" => "mdl_portfolio_mahara_queue", "pk" => "id"],
    ["table" => "mdl_search_simpledb_index", "pk" => "id"],
    ["table" => "mdl_tool_brickfield_checks", "pk" => "id"],
    ["table" => "mdl_tool_brickfield_process", "pk" => "id"],
    ["table" => "mdl_tool_brickfield_areas", "pk" => "id"],
    ["table" => "mdl_tool_brickfield_content", "pk" => "id"],
    ["table" => "mdl_tool_brickfield_results", "pk" => "id"],
    ["table" => "mdl_tool_brickfield_errors", "pk" => "id"],
    ["table" => "mdl_tool_brickfield_summary", "pk" => "id"],
    ["table" => "mdl_tool_brickfield_cache_check", "pk" => "id"],
    ["table" => "mdl_tool_brickfield_cache_acts", "pk" => "id"],
    ["table" => "mdl_tool_brickfield_schedule", "pk" => "id"],
    ["table" => "mdl_tool_cohortroles", "pk" => "id"],
    ["table" => "mdl_tool_customlang", "pk" => "id"],
    ["table" => "mdl_tool_customlang_components", "pk" => "id"],
    ["table" => "mdl_tool_dataprivacy_request", "pk" => "id"],
    ["table" => "mdl_tool_dataprivacy_purpose", "pk" => "id"],
    ["table" => "mdl_tool_dataprivacy_category", "pk" => "id"],
    ["table" => "mdl_tool_dataprivacy_ctxinstance", "pk" => "id"],
    ["table" => "mdl_tool_dataprivacy_ctxlevel", "pk" => "id"],
    ["table" => "mdl_tool_dataprivacy_ctxexpired", "pk" => "id"],
    ["table" => "mdl_tool_dataprivacy_purposerole", "pk" => "id"],
    ["table" => "mdl_tool_dataprivacy_contextlist", "pk" => "id"],
    ["table" => "mdl_tool_dataprivacy_ctxlst_ctx", "pk" => "id"],
    ["table" => "mdl_tool_dataprivacy_rqst_ctxlst", "pk" => "id"],
    ["table" => "mdl_tool_mfa", "pk" => "id"],
    ["table" => "mdl_tool_mfa_secrets", "pk" => "id"],
    ["table" => "mdl_tool_mfa_auth", "pk" => "id"],
    ["table" => "mdl_tool_monitor_rules", "pk" => "id"],
    ["table" => "mdl_tool_monitor_subscriptions", "pk" => "id"],
    ["table" => "mdl_tool_monitor_history", "pk" => "id"],
    ["table" => "mdl_tool_monitor_events", "pk" => "id"],
    ["table" => "mdl_tool_policy", "pk" => "id"],
    ["table" => "mdl_tool_policy_versions", "pk" => "id"],
    ["table" => "mdl_tool_policy_acceptances", "pk" => "id"],
    ["table" => "mdl_tool_recyclebin_course", "pk" => "id"],
    ["table" => "mdl_tool_recyclebin_category", "pk" => "id"],
    ["table" => "mdl_tool_usertours_tours", "pk" => "id"],
    ["table" => "mdl_tool_usertours_steps", "pk" => "id"],
    ["table" => "mdl_paygw_paypal", "pk" => "id"],
    ["table" => "mdl_assignsubmission_file", "pk" => "id"],
    ["table" => "mdl_assignsubmission_onlinetext", "pk" => "id"],
    ["table" => "mdl_assignfeedback_comments", "pk" => "id"],
    ["table" => "mdl_assignfeedback_editpdf_cmnt", "pk" => "id"],
    ["table" => "mdl_assignfeedback_editpdf_annot", "pk" => "id"],
    ["table" => "mdl_assignfeedback_editpdf_quick", "pk" => "id"],
    ["table" => "mdl_assignfeedback_editpdf_rot", "pk" => "id"],
    ["table" => "mdl_assignfeedback_file", "pk" => "id"],
    ["table" => "mdl_ltiservice_gradebookservices", "pk" => "id"],
    ["table" => "mdl_quiz_overview_regrades", "pk" => "id"],
    ["table" => "mdl_quiz_statistics", "pk" => "id"],
    ["table" => "mdl_quizaccess_seb_quizsettings", "pk" => "id"],
    ["table" => "mdl_quizaccess_seb_template", "pk" => "id"],
    ["table" => "mdl_workshopform_accumulative", "pk" => "id"],
    ["table" => "mdl_workshopform_comments", "pk" => "id"],
    ["table" => "mdl_workshopform_numerrors", "pk" => "id"],
    ["table" => "mdl_workshopform_numerrors_map", "pk" => "id"],
    ["table" => "mdl_workshopform_rubric", "pk" => "id"],
    ["table" => "mdl_workshopform_rubric_levels", "pk" => "id"],
    ["table" => "mdl_workshopform_rubric_config", "pk" => "id"],
    ["table" => "mdl_workshopallocation_scheduled", "pk" => "id"],
    ["table" => "mdl_workshopeval_best_settings", "pk" => "id"],
    ["table" => "mdl_tiny_autosave", "pk" => "id"],
    ["table" => "mdl_logstore_standard_log", "pk" => "id"],
];

const INSTRUMENT_SNAPSHOT_COLUMN_COUNT = 2;
const INSTRUMENT_SNAPSHOT_XMIN_ALIAS = '__nomai_xmin';
const INSTRUMENT_SNAPSHOT_XMAX_ALIAS = '__nomai_xmax';

$GLOBALS['INSTRUMENT_READ_SEQUENCE'] = 0;

function nextInstrumentReadSequence(): int {
    $seq = $GLOBALS['INSTRUMENT_READ_SEQUENCE'] ?? 0;
    $GLOBALS['INSTRUMENT_READ_SEQUENCE'] = $seq + 1;
    return $seq;
}

class RustSqlRewriter {
    private static $ffi = null;
    private static $instance = null;
    
    // Configure your .so path
    const SO_PATH = '/var/www/html/lib/dml/librust_sql_rewriter.so';
    
    // Moodle table primary-key configuration (example)
    const TABLE_CONFIG = INSTRUMENT_TABLE_CONFIG;

    private function __construct() {
        if (!file_exists(self::SO_PATH)) {
            error_log("[RustRewriter] .so file not found: " . self::SO_PATH);
            return;
        }

        try {
            // Define the C interface signature
            $cdef = "
                typedef struct {
                    char* new_sql;
                    char* meta_json;
                    char* error_msg;
                } RewriteResult;

                int init_config(const char* json);
                RewriteResult rewrite_sql(const char* sql);
                void free_rewrite_result(RewriteResult res);
            ";

            self::$ffi = FFI::cdef($cdef, self::SO_PATH);

            // Initialize configuration
            $json_config = json_encode(self::TABLE_CONFIG);
            if (self::$ffi->init_config($json_config) != 0) {
                error_log("[RustRewriter] Failed to init config");
            } else {
                error_log("[RustRewriter] Initialized successfully");
            }
        } catch (Exception $e) {
            error_log("[RustRewriter] FFI Load Error: " . $e->getMessage());
            self::$ffi = null;
        }
    }

    public static function getInstance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Call Rust to rewrite SQL
     * @return array [string|null $new_sql, array $meta_list]
     */
    public function rewrite($sql) {
        if (!self::$ffi) {
            return [null, []];
        }
        if (stripos(trim($sql), 'SELECT') !== 0) {
            return [null, []];
        }

        try {
            $res = self::$ffi->rewrite_sql($sql);
            
            $new_sql = null;
            $meta = [];

            if ($res->error_msg !== null) {
                // $err = FFI::string($res->error_msg);
                // error_log("[RustRewriter] Rewrite error: $err");
            } elseif ($res->new_sql !== null) {
                $new_sql = FFI::string($res->new_sql);
                if ($res->meta_json !== null) {
                    $json_str = FFI::string($res->meta_json);
                    $meta = json_decode($json_str, true) ?? [];
                }
            }

            // Release memory allocated on the Rust side
            self::$ffi->free_rewrite_result($res);

            return [$new_sql, $meta];
        } catch (Exception $e) {
            error_log("[RustRewriter] Call Error: " . $e->getMessage());
            return [null, []];
        }
    }
}